Add full logic for the game
ammarkandel/Tic-Tac-Toe-Game pull request #5
Opened 2021-01-14 20:27 UTC by ammarkandel

Add full logic about the game : 
                                                  - Check which player win
                                                  - Check if the player enter a valid number
                                                  - Check for available numbers for the next player
                                                  - Display the player input into the board

2021-01-15 00:17 UTC, BrianSammit requested changes
CHANGE REQUIRED :recycle:  
Great work team!! :+1: the game is working well. :smile: 
However, there are a few changes that you have to work on. 
------------------------------------

- [x] The game logic should be in the lib directory 

![Screenshot from 2021-01-14 19-05-35](https://user-images.githubusercontent.com/64173189/104663683-84a11180-569b-11eb-944f-ead6d6768391.png)

- [x] Use at least two classes to encapsulate different parts of game logic.

![Screenshot from 2021-01-14 19-08-43](https://user-images.githubusercontent.com/64173189/104663867-eeb9b680-569b-11eb-9dd4-57384c0da0d1.png)

---------------------

Made these changes and request another review. :clap: 
HAPPY CODING!! 

![MB5W4D](https://user-images.githubusercontent.com/64173189/104664342-fc237080-569c-11eb-8196-ffc72ea1ce07.gif)

2021-01-16 01:52 UTC, BrianSammit requested changes
CHANGE REQUIRED :recycle:  
I can't start the game and the lib directory is empty check your commit, it could be a problem pushing the project.

Made these changes and request another review. :clap: 
HAPPY CODING!! 

![programming](https://user-images.githubusercontent.com/64173189/104794097-83431800-5773-11eb-88d9-2e897fb19f38.gif)

2021-01-16 14:57 UTC, LamiaSristy requested changes
# Status: Change Required. 🔴 

Hello Team, Great work so far, 🙌 .

Your game's win logic and checking draw is working perfectly, but there is a major fault in Please check my points here: 👇

-  [ ]  After any invalid input your game is switching the sign, but it should not. Like, if I am pressing 1 it is printing X, and again if I press 1, It's printing "Number 1 is an invalid number.", but if I press 2 next time it is again printing X in position 2, which should be O in position 2.
- [ ] With every time the board is printing it is also printing nil, please remove it.
- [x]  All game-logic related resources (classes and/or modules) are kept in the `lib` directory. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone1/lib_dir_exist.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))
Currently, your main is responsible for many logics please remove them inside 'lib' and you can make different classes for individual work, as board, winning method, game, etc.

- [Optional] 

- [ ] Currently, your game is not taking any players name, so it is difficult for the user to play without the name, consider adding logic for taking player names, and printing it with every move.

Once you make the changes, please ask again for a re-review.
Feel free to reach me at @lamiasristy 🙋

2021-01-16 21:44 UTC, GzimAsani requested changes
### CHANGES REQUIRED  :stop_sign: 
### HELLO  **TEAM**  I like your project and you did a great job implementing the changes from the last review :+1:  very nice work :+1:  but unfortunately there are some requirements that you did not implement from the last reviews:
- [x]  _With every time the board is printing it is also printing nil, please remove it._
- [ ] _All game-logic related resources (classes and/or modules) are kept in the lib directory. (screenshot from Pathwright) Currently, your main is responsible for many logics and includes one class, please remove it_

### Also:
- [ ] Please use attr_readers/attr_writers instead of attr_accessors because by using attr_accessors you allow writing that property from outside the class. That variable can be set to anything and this means that your variables can be over-written from anywhere in the application.

- [OPTIONAL]
- [ ] _Currently, your game is not taking any players name, so it is difficult for the user to play without the name, consider adding logic for taking player names, and printing it with every move._

### **Please make the required changes and submit another review request when you are ready.**

<hr>
### if you have any question kindly reach me on slack @GzimAsani

### HAPPY CODING :computer:

2021-01-17 02:16 UTC, kevincappuccino requested changes
# [STATUS] CHANGES REQUESTED ♻

### Hey, nice project so far. We only have to improve a few things before moving on:

You have `p` outside the main file, on: `check_game_result.rb`, `start_game_vars.rb`, and `start_game`;
- [ ] No `puts/print` and `gets.chomp` outside `main.rb` file. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/only_main_print.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))
- [ ] You still have logic in your main file, please note that the main should represent the view of your project, so keep in mind that you should only use it only for i/o and loops. Keep the `invalid` method outside the main file.
- [x] Here we have three errors, please fix them:
![image](https://user-images.githubusercontent.com/56762529/104829104-43516300-584f-11eb-87f5-1002cbdab2d3.png)
1- After we chose 1, you print "Type number from 1 to 9", but 1 was already taken;
2- If we chose 1 again, your project prints: "Number 1 is invalid number.", which is not true, is a valid number, what is invalid is the move. The same happens when we type a letter;
3- We have typo errors: "Number 1 is invalid number." should be: "Number 1 is **_an_** invalid ~number~ **move**." And "Type **_a_** number from 1 to 9";

⚠ Its wired that you aren't using the user interface in this project, It should ask our names and print the board with numbers to make easy to visualize the spaces to select. But since it's not explicit mandatory, I'll not ask for it;



## As always, I wish you all the very best and see you both at the top🚀


👨🏻‍💻 **TSE: Kevin Alves**

  

📫 Have any question? Better call Kevin:

<a  href="mailto:kevinalves.js@gmail.com"> <img  alt="gmail"  src="https://img.shields.io/badge/gmail-%20- green?logo=gmail&style=social"></a> [![Twitter Follow](https://img.shields.io/twitter/follow/kevinnnmn?style=social)](https://twitter.com/intent/follow?screen_name=kevinnnmn) [![](https://img.shields.io/badge/Slack-Kevin%20Alves-green?logo=slack&style=social)](https://microverse-students.slack.com/team/UT86D3AP4)

2021-01-17 08:20 UTC, blackpintz requested changes
# Status: Changes Required 🛑

## Hello team 👋,

**Great job implementing the requested changes 👏. However, there are still a few requirements needed.**

1). **As the previous TSE mentioned, when a number between 1-9  is chosen again, it should not say that that number is invalid but that the move is invalid or number is already taken.**
2). **When I play a value that is not a number, e.g d or ., I get an error: 'Number 0 is an invalid number. Please alert the user on the right invalid move.'**
3). **I played a first good move and followed that with four bad moves. The fifth move was a good move but it didn't change the player symbol. It used the X symbol instead of O symbol. Check the screenshot below.**

 screenshot1 | screenshot2
 --------------| -------------
![screenshot1](https://user-images.githubusercontent.com/38922385/104834638-d327f900-58b1-11eb-873c-8a6a9932855a.png) | ![screenshot2](https://user-images.githubusercontent.com/38922385/104834649-e1761500-58b1-11eb-8599-d3449bf89968.png)

4). **Game related logic like classes/modules should be added in the `lib` directory and not `main .rb` file. Please fix that.**

5). **Check more in the comments below.**

### Happy coding 🥂.

**PS: You can reach me on slack (Rose Wanjohi).**

2021-01-17 08:20 UTC, blackpintz commented on lib/start_game.rb
> +        break
You should not use any function that prints to the console outside of `main.rb`. That includes `p`.

2021-01-17 08:20 UTC, blackpintz commented on lib/start_game_vars.rb
> +    p "These numbers are avaliable for next player #{@avaliable}"
You should not use any function that prints to the console outside of `main.rb`. That includes `p`.

2021-01-17 08:20 UTC, blackpintz commented on lib/check_game_result.rb
> +  end
Add `attr_readers/attr_writers/attr_accessors` for the above class instance variables.

2021-01-17 15:27 UTC, Temmarie approved these changes
## Status: Approved :heavy_check_mark:

### Hi @ammarkandel  ! :wave:

#### Thank you for making all of the required changes, your project is approved :clap: :clap: :clap: :tada:

**Optional**

- [ ]  When I play a value that is not a number, e.g "d, p,.-", I should get an error: "Invalid input" 

#### You may merge, good luck with your next projects! :rocket:
#### Happy Coding! :+1:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

2021-01-17 15:29 UTC, merged