Test public methods
ammarkandel/Tic-Tac-Toe-Game pull request #7
Opened 2021-01-19 19:22 UTC by ammarkandel

Test the public methods and check the cases if one of the players wins or not used it block inside describe block and it block for every test aspect.

2021-01-19 20:12 UTC, enaburekhan reviewed
# Invalid
Friendly reminder: You should make sure that your pull request  looks professional before review.
Please take a step back and read a lesson here https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/.
Then apply 3 simple rules from this lesson (it will be easy as you can use a template provided there).
This Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready!

You can reach me on slack on @enaburekhan eric 

Happy coding!!!

2021-01-19 20:48 UTC, NtwaliHeritier requested changes
### STATUS: CHANGES REQUESTED ### 
Hello team,
Great work so far, however changes are required.
[REQUIRED] Try adding more test cases.
As a tip, you can add negative test cases.

Do the required changes and ask for another review.

2021-01-19 22:54 UTC, enaburekhan requested changes
# Changes Requested :globe_with_meridians:
**Great job so far :clap:. However, there are some changes we need to make to get this project approved :muscle:.**

- Just as the previous Tse pointed out, your test cases are too few. Try to also look at negative events in the course of playing your game and write tests to cater for such events.

All methods implemented in the Enumerables project are tested ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/Ruby_testing/all_enumerables.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/testing-your-ruby-code))

All the public methods of the classes implemented in project OOP are tested ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/Ruby_testing/all_tic_tac_toe.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59566098/))

Kindly make the required changes using the above guidelines and resubmit for another review.

You can reach me on slack @enaburekhan, if you have any questions.

Happy coding!!! :blush:

2021-01-19 22:54 UTC, enaburekhan commented on spec/check_game_result_spec.rb
> +end
Kindly add more tests, most especially negative tests cases:pray:

2021-01-20 14:26 UTC, BrianSammit approved these changes
APPROVED :clap: :green_circle: 
------------
HELLO TEAM!!! Nice job working on the required changes. :muscle: 
--------------
Good luck with the next project. :four_leaf_clover: 
HAPPY CODING!!

![200](https://user-images.githubusercontent.com/64173189/105188016-728efb00-5b01-11eb-81cb-49c893d1efc7.gif)

2021-01-20 14:57 UTC, merged